scan_topic: "/scan"
nav_topic: "/vesc/high_level/ackermann_cmd_mux/output"
safety_topic: "/vesc/low_level/ackermann_cmd_mux/input/safety"
safety_margin: 0.5
car_front_right: [0.2, -0.15]
car_front_left: [0.2, 0.15]
error: 5
