# A reasonable number to start with
num_particles: 200

# The number of lidar beams emitted from
# each particle. This doesn't need to be
# equal to the actual number (>1000)
# so long as you downsample properly
num_beams_per_particle: 100

# The field of view centered around theta=0
scan_field_of_view: 4.71 # radians

# Discretize the theta space for faster ray tracing
scan_theta_discretization: 500

# The names of topics to listen and publish to
map_topic: "/map"
scan_topic: "/scan"
odom_topic: "/vesc/odom"

# The frame you should publish your transform to.
particle_filter_frame: "/base_link"


delay_to_draw_path: 7

best_choice_alg: 0 #1 is the highest prob, 0 is average
x_sd: 0.04
y_sd: 0.04
t_sd: 0.04

click_xy_sd: 0.5
click_t_sd: 0.5

a_hit: 0.65
a_short: 0.3
a_max: 1
a_rand: 0.05

on_robot: 1 #1 is on robot, 0 is sim
